version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: ecommerce
    ports:
      - "4000:4000"
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  db_data:
